# Site
repository: dingonewen/dingonewen.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yiwen Ding
title: Humor Retriever
email: dingywn@seas.upenn.edu
phone: (607)379-1110
website: https://dingonewen.github.io

# Dark Mode (true/false/never)
darkmode: never

# Social links
facebook_username: yiwen.ding.2025
instagram_username: dingonewen
linkedin_username: dingyiwen
orcid_username: 0000-0002-9611-623X
googlescholar_username: citations?user=8F-heNYAAAAJ&hl=en

# Additional icon links
#additional_links:
#- title: Reddit
#  icon: fa-reddit
#  url: https://www.reddit.com/user/Delicious-Factor551/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Generally Speaking
about_profile_image: images/weixinphoto.jpg
about_content: | # this will include new lines to allow paragraphs
 <p style="text-indent: 2em;"> I’m not much of a talker in person, but I enjoy showing off my humor in chats. I like to call myself a <strong>Humor Retriever</strong> — loyal to the joke, always chasing the laugh. The only thing that truly unsettles me is meeting someone funnier than I am.

 <p style="text-indent: 2em;"> Before college, my favorite subject was Physics. I did fairly well in it, but I decided to major in something that felt more... digestible — <mark>Food Science</mark>. Since I’ve always dreamed of running a restaurant, it turned out to be a surprisingly good fit, and I gained a solid foundation in scientific thinking.

 <p style="text-indent: 2em;"> After three years in biotech — and more ups and downs than I can count — I decided to pivot to <mark>Computer Science</mark> at Penn following a two-year deferral. It’s not every day you get a second chance at education after joining the workforce, and I’m genuinely grateful for it. Despite the challenging job market, I remain optimistic. I prepare for the worst, hope for the best, and debug everything in between — that’s my philosophy for both code and life.

 <p style="text-indent: 2em;"> I’m currently honing my programming skills and seeking a 2026 summer internship as a <mark>Technical Project Manager</mark> or <mark>Software Developer</mark>. If you’d like to get to know me better — or, as some call it, “an interview” — feel free to reach out by email. I check my inbox approximately three times per second.

content:

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: University of Pennsylvania
        sub_title: Master of Computer & Information Technology
        caption: Aug 2025 - May 2027 (expected)
        quote: >
          "<a href='https://www.upenn.edu/' target='_blank'>Leges sine moribus vanae.</a>"
        description: | # this will include new lines to allow paragraphs
          | GPA: TBD
          | Thriving through learning...
          | Courses: Software Development, Computer Systems, Data Structure & Algorithm (Spring 2026) 
      - layout: top-right
        title: Cornell University
        sub_title: Bachelor of Science in Food Science
        caption: Aug 2018 - May 2022
        quote: >
          "<a href='https://www.cornell.edu/' target='_blank'>I would found an institution where any person can find instruction in any study.</a>"
        description: | # this will include new lines to allow paragraphs
          | MAGNA CUM LAUDE
          | Member of CALS Honor Society
          | Major GPA: 3.9; Minor GPA: 4.0
          | Courses: Product Development, Spreadsheet Modeling, Market Research
      - layout: top-right
        title: China Agricultural University
        sub_title: Bachelor of Engineering in Food Science & Engineering
        caption: Aug 2018 - Nov 2022
        quote: >
          "<a href='https://cau.edu.cn/' target='_blank'>解民生之多艰，育天下之英才。</a>"
        description: | # this will include new lines to allow paragraphs
          | Dual Degree Program
          | Top 1% student
          | Courses: Principles of Mechanics, Linear Algebra, all bio & Chem & Phys

  - title: Experience
    layout: list
    content:
      - layout: right
        title: "<a href='https://www.amerigoscientific.com/' target='_blank'>Amerigo Scientific</a>"
        sub_title: Project Manager
        caption: Jun 2023 - May 2025
        quote: >
          A worldwide e-commerce and distribution company in biotech that connects global suppliers and clients. 
        description: | # this will include new lines to allow paragraphs
          | Directed business development, sales operations, and logistics, driving growth initiatives and improving operational efficiency
          | Negotiated partnership agreements with 100+ global companies, contributing to 85% of total sales revenue
          | Implemented email marketing automation with JavaScript and analyzed customer data using Python to optimize sales strategies
          | Represented the company at major U.S. pharmaceutical and biotech conferences; trained staff on market trends and adapted strategies to industry developments

      - layout: right
        title: "<a href='https://www.kobrienlab.com/' target='_blank'>Cornell University, O'Brien Lab</a>"
        sub_title: Clinical Research Coordinator
        caption: Dec 2022 - Jun 2023
        quote: >
          We help characterize the nutritional, genetic and hormonal determinants of mineral metabolism on maternal and child health.
        description: | # this will include new lines to allow paragraphs
          | Initiated role through onsite internship (Jun – Aug 2022) and was invited to return as a part-time remote coordinator to continue supporting clinical studies
          | Recruited, screened, and retained human subjects, ensuring compliance with clinical research protocols and IRB requirements
          | Coordinated participant scheduling and visits; assisted with IRB submissions, protocol development, and SOP documentation
          | Performed statistical data analysis of dietary recall datasets using Python, R, and JMP to support research outcomes
          | Oversaw biospecimen handling, storage, and quality control; managed lab operations and collaborated closely with PI and study team

      - layout: right
        title: "<a href='https://www.eurofinsus.com/' target='_blank'>Eurofins Lancaster Laboratories</a>"
        sub_title: Associate Scientist
        caption: Aug 2022 - Dec 2022
        quote: >
          A global independent market leader in genomics, clinical studies and BioPharma Contract Development and Manufacturing.
        description: | # this will include new lines to allow paragraphs
          | Trained in Laboratory Information Management Systems (LIMS), Electronic Laboratory Notebooks (ELN), and Standard Operating Procedures (SOPs)
          | Performed client sample testing and assay development in a BSL-2 environment, adhering to cGMP/GLP and USP guidelines.
          | Operated, calibrated, and maintained HPLC, CE, osmometer, turbidimeter, and UV-Vis spectrophotometer
          | Presented assay development progress and sample analysis results to senior management, aligning tasks with departmental goals

  - title: Projects
    layout: list
    content:
      - layout: left
        border: weak
        title: Blackjack Solitaire
        link: https://github.com/dingonewen/mini-projects/tree/main/blackjack_solitaire
        link_text: Blackjack Solitaire
        additional_links:
          - title: Blackjack Solitaire
            icon: fab fa-github
            url: https://github.com/dingonewen/mini-projects/tree/main/blackjack_solitaire
        quote: >
          "21, baby!"
        description: | # this will include new lines to allow paragraphs
          | A Java implementation of a one-player card game called Blackjack Solitaire, where the player attempts to build hands with values as close to 21 as possible without exceeding 21.

      - layout: left
        border: weak
        title: Uno
        link: https://github.com/dingonewen/mini-projects/tree/main/uno
        link_text: Uno
        additional_links:
          - title: Uno
            icon: fab fa-github
            url: https://github.com/dingonewen/mini-projects/tree/main/uno
        quote: >
            "Uno!"
        description: | # this will include new lines to allow paragraphs
          | A Java implementation of the classic UNO card game, featuring support for 2-4 players with both human and computer opponents.
          
      - layout: left
        border: weak
        title: Clinical Research
        link: https://www.kobrienlab.com/
        link_text: O'Brien Lab
        additional_links:
          - title: DHA Chicken Study
            icon: fas fa-drumstick-bite
            url: https://docs.google.com/presentation/d/1rpmDe5bwRldBRT27xEp8IaYSuEWT5N2V/edit?usp=sharing&ouid=110493095619593127092&rtpof=true&sd=true
        quote: >
          Bioavailability of Docosahexaenoic Acid From Biofortified Chicken
          
        description: |
          | Participated in the Empowering U.S. Broiler Production for Transformation and Sustainability project with a grant from USDA
          | Analyzed and interpreted fatty acids content in human studies using JMP and Excel, gained expertise in JMP
          | Completed an oral presentation and poster session titled Bioavailability of DHA From Biofortified Chicken

          <img src="/images/Bioavailability of DHA poster.jpg" alt="Research Poster" style="float: right; width: 300px; margin: 0 0 15px 15px; border-radius: 8px;">
      
      - layout: left
        border: weak
        title: Microbiology Research
        link: https://www.zhenghaolab.org/
        link_text: Zheng Lab
        additional_links: 
          - title: Gut Microbiota
            icon: fas fa-bacterium
            url: https://doi.org/10.1111/1744-7917.12770
        quote: >
            Even the gut microbiota of honeybees is powerful.
        description: | # this will include new lines to allow paragraphs
          | Our results illustrate the prevalence of strain-level variations in the metabolic potentials and the distributions of antibiotic-resistant genes in Chinese bumblebee gut bacteria
          | Performed honeybee dissections, sample collection, PCR sequencing, and meta-analysis of sequencing data; contributed over 30 hours per week to lab research
          | Portions of my work were incorporated into an additional publications on "<a href='https://doi.org/10.1073/pnas.1916224116' target='_blank'>PNAS</a>", contributing to the study of gut microbiota
          
  - title: More About Me          
    layout: text
    content: | # this will include new lines to allow paragraphs
      <img src="/images/soccerfood.jpg" alt="Soccer and Food" style="float: right; width: 300px; margin: 0 0 15px 15px; border-radius: 8px;">
      
      <p style="text-indent: 2em;">I tend to live a fairly structured and disciplined life, but outside of work and study, I have a few simple joys — <em>free food</em>, <em>quality sleep</em>, and watching <em>soccer</em> games.</p>
      
      <p style="text-indent: 2em;">I'm currently preparing to volunteer at the FIFA 2026 World Cup in Philadelphia. I steer clear of high-impact workouts — mostly because I'd like to keep all my joints intact — so swimming has become my sport of choice. When life slows down, I swim about 25 km a month.</p>
      
      <p style="text-indent: 2em;">I'm an early-to-bed, early-to-rise kind of person — late nights and I simply don't get along. I enjoy calm, mellow <em>music</em>, and my favorite artist and producer is <a href="https://khalilfong.com/2017/" target="_blank">Khalil Fong</a>.</p>
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
